[platformio]
default_envs = xiao_rp2040_check

[env:xiao_rp2040_check]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino
monitor_speed = 115200
build_flags =
    -D SERIAL_MONITOR_SPEED=115200
